---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-cloud-config
  namespace: kube-system
type: Opaque
stringData:
  cloud-config: '
  {
    "token": "55b4c52123462dk23sa165cc3dba1234123125666f1422c8",
    "clusterID": 13928,
    "apiVersion": "v4",
    "baseURL": "api.linode.com"
  }'
